language: rust

rust:
#  - stable
  - beta
  - nightly

services:
  - elasticsearch

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ruby

# As recommended here: http://docs.travis-ci.com/user/database-setup/#ElasticSearch
before_script:
  - sleep 10
