language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls

rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ruby
  - curl -O https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.0.2/elasticsearch-2.0.2.deb && sudo dpkg -i --force-confnew elasticsearch-2.0.2.deb
  - sudo service elasticsearch start

# As recommended here: http://docs.travis-ci.com/user/database-setup/#ElasticSearch
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
  - sleep 10

script:
    - |
        travis-cargo build &&
        travis-cargo test

after_success:
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  - travis-cargo coveralls --no-sudo --verify

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - RUST_BACKTRACE=1
