language: rust

sudo: false

addons:
  apt:
    packages:
      - ruby

rust:
  - stable
  - beta
  - nightly

services:
  - elasticsearch

# As recommended here: http://docs.travis-ci.com/user/database-setup/#ElasticSearch
before_script:
  - sleep 10
