language: rust

rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ruby
  - curl -O https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.0.2/elasticsearch-2.0.2.deb && sudo dpkg -i --force-confnew elasticsearch-2.0.2.deb
  - sudo service elasticsearch start

# As recommended here: http://docs.travis-ci.com/user/database-setup/#ElasticSearch
before_script:
  - sleep 10

script:
  - curl -XPUT 'http://localhost:9200/newidx/newtype/1' -d '{"hello": "value"}'
