language: rust
rust:
  - stable
  - beta
  - nightly
script: make test
services:
  - elasticsearch
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ruby
before_script:
  - sleep 10