[package]
name = "rs-es"
version = "0.11.0"
authors = ["Ben Ashford"]
license = "Apache-2.0"
repository = "https://github.com/benashford/rs-es"
description = "Client for the ElasticSearch REST API"
readme = "README.md"
keywords = ["elasticsearch", "elastic"]
exclude = ["devbox/**/*", "docker-dev.yml"]

[lib]
name = "rs_es"

[features]
default = ["ssl"]
ssl = ["hyper-openssl"]

[dependencies]
hyper = "^0.10"
hyper-openssl = { version = "^0.2", optional = true }
log = "0.4.6"
maplit = "1.0.1"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
url = "1.7.1"

[dev-dependencies]
env_logger = "0.5.13"
regex = "1.0.5"
