[package]
name = "rs-es"
version = "0.3.0"
authors = ["Ben Ashford"]
license = "Apache-2.0"
repository = "https://github.com/benashford/rs-es"
documentation = "http://benashford.github.io/rs-es/rs_es/index.html"
description = "Client for the ElasticSearch REST API"
readme = "README.md"
keywords = ["elasticsearch", "elastic"]
exclude = ["devbox/**/*", "docker-dev.yml"]
build = "build.rs"

[lib]
name = "rs_es"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]

[build-dependencies]
quasi = {git = "https://github.com/benashford/quasi", branch = "experimental"}
serde_codegen = {git = "https://github.com/benashford/serde", branch = "experimental", optional = true}
syntex = {git = "https://github.com/benashford/syntex", branch = "experimental"}

[dependencies]
hyper = "^0.7"
rustc-serialize = "^0.3"
log = "^0.3"
maplit = "^0.1"
serde = {git = "https://github.com/benashford/serde", branch = "experimental"}
serde_json = {git = "https://github.com/benashford/json", branch = "experimental"}
serde_macros = {git = "https://github.com/benashford/serde", branch = "experimental", optional = true}

[dev-dependencies]
env_logger = "^0.3"
regex = "^0.1"
