[package]
name = "rs-es"
version = "0.1.0"
authors = ["Ben Ashford"]
licence = "Apache-2.0"
repository = "https://githib.com/benashford/rs-es"
description = "Client for the ElasticSearch REST API"
readme = "README.md"
keyword = ["elasticsearch", "elastic"]

[lib]
name = "rs_es"

[dependencies]
hyper = "*"
rustc-serialize = "*"
log = "*"

[dev-dependencies]
env_logger = "*"
regex = "*"
