[package]
name = "rs-es"
version = "0.2.1"
authors = ["Ben Ashford"]
license = "Apache-2.0"
repository = "https://github.com/benashford/rs-es"
documentation = "http://benashford.github.io/rs-es/rs_es/index.html"
description = "Client for the ElasticSearch REST API"
readme = "README.md"
keywords = ["elasticsearch", "elastic"]
build = "build.rs"

exclude = ["devbox/**/*", "docker-dev.yml"]

[lib]
name = "rs_es"

[dependencies]
hyper = "^0.7"
rustc-serialize = "^0.3"
log = "^0.3"

[dev-dependencies]
env_logger = "^0.3"
regex = "^0.1"
