[package]
name = "rs-es"
version = "0.1.13"
authors = ["Ben Ashford"]
license = "Apache-2.0"
repository = "https://github.com/benashford/rs-es"
documentation = "http://benashford.github.io/rs-es/rs_es/index.html"
description = "Client for the ElasticSearch REST API"
readme = "README.md"
keywords = ["elasticsearch", "elastic"]
build = "build.rs"

exclude = ["devbox/**/*", "docker-dev.yml"]

[lib]
name = "rs_es"

[dependencies]
hyper = "*"
rustc-serialize = "*"
log = "*"

[dev-dependencies]
env_logger = "*"
regex = "*"
